"""init soft delete

Revision ID: 9fb7804e31a5
Revises: 386071713d29
Create Date: 2026-02-14 14:52:47.996790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb7804e31a5'
down_revision: Union[str, Sequence[str], None] = '386071713d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('suppliers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'is_deleted')
    op.drop_column('products', 'is_deleted')
    op.drop_column('categories', 'is_deleted')
    # ### end Alembic commands ###
