"""

Revision ID: c765d0204833
Revises: 1cd27883de6e
Create Date: 2026-02-15 18:58:09.829526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c765d0204833'
down_revision: Union[str, Sequence[str], None] = '1cd27883de6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        'products',
        sa.Column('price', sa.Float(), nullable=False, server_default=sa.text("0"))
    )

    op.alter_column('products', 'price', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
